name: Testing_github_runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: minikube_runner
    container:
      image: ubuntu:latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Echo Message
      run: echo "Hello World"